[Renaming HB] 4. Renaming Harbourbridge to Spanner migration tool - All import statements and URLs
GoogleCloudPlatform/spanner-migration-tool pull request #592
Opened 2023-07-20 07:12 UTC by darshan-sj

[4. Renaming Harbourbridge to Spanner migration tool - All import statements and github URLs 

…ll import statements, github URLs

- [ ] Tests pass
- [ ] Appropriate changes to README are included in PR

2023-07-20 11:01 UTC, bharadwaj-aditya requested changes

2023-07-21 06:21 UTC, darshan-sj commented on Makefile
> +	go build -o harbourbridge
This is related to harbourbridge command. I'll rename the harbourbridge command in an upcoming PR

2023-07-21 06:22 UTC, darshan-sj commented on README.md
> +[![integration-tests-against-emulator](https://github.com/GoogleCloudPlatform/spanner-migration-tool/actions/workflows/integration-tests-against-emulator.yaml/badge.svg)](https://github.com/GoogleClo
Other mentions of Harbourbridge in the readme files are being corrected in first PR -- https://github.com/GoogleCloudPlatform/spanner-migration-tool/pull/583

2023-07-21 06:42 UTC, bharadwaj-aditya approved these changes
LGTM

2023-07-21 08:57 UTC, merged